name: Unity Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 디스크 공간 정리
      - name: Clean up disk space before build
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker system prune -af
          sudo rm -rf /usr/local/lib/android/sdk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android/sdk
          sudo rm -rf /opt/ghc
          
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

     # JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

     # NDK 설치
      - name: Set up Android NDK
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT/ndk-bundle
          sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "ndk;21.4.7075529"
          sudo ln -s $ANDROID_SDK_ROOT/ndk/21.4.7075529 $ANDROID_SDK_ROOT/ndk-bundle

      # 키스토어 설정
          
      # Unity 설정 및 빌드
      - name: Setup and Build Unity
        uses: game-ci/unity-builder@v4
        with:
          version: 2023.2.20f1
          targetPlatform: Android
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 아티팩트 업로드
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
