name: Unity Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 빌드 후 디스크 정리
      - name: Clean up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker system prune -af
          
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # Docker 설정 (필요한 경우에만)
      - name: Setup Docker
        run: docker build -t unity-ci -f Dockerfile .

      # Unity 설정 및 빌드
      - name: Setup and Build Unity
        uses: game-ci/unity-builder@v4
        with:
          version: 2023.2.20f1
          targetPlatform: Android
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Android 빌드 준비 (필요한 경우에만)
      - name: Setup Android
        uses: android-actions/setup-android@v3.2.1
        with:
          java-version: 11

      # 키스토어 설정
      - name: Set up Keystore
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > user.keystore

      # 아티팩트 업로드
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
