name: Unity Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android

      # Unity 설정 및 빌드
      - name: Setup and Build Unity
        uses: game-ci/unity-builder@v4
        with:
          version: 2023.2.20f1
          targetPlatform: Android
          customParameters: '-keystore $HOME/my-release-key.keystore -keystorePassword ${{ secrets.KEYSTORE_PASSWORD }} -keyalias ${{ secrets.KEYSTORE_ALIAS }} -keyPassword ${{ secrets.KEY_PASSWORD }}'
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          androidExportType: 'androidPackageapk'
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE }}
          androidKeystorePass: ${{ secrets.KEYSTORE_PASSWORD }}
          androidKeyaliasName: ${{ secrets.KEYSTORE_ALIAS }}
          androidKeyaliasPass: ${{ secrets.KEY_PASSWORD }}
          androidTargetSdkVersion: AndroidApiLevel30
          
      - uses: actions/upload-artifact@v3
        with:
          name: build-Android
          path: build/Android
