name: Build on iOS

on:
  push:
    branches:
      - main

jobs:
  buildForiOSPlatform:
    name: Build for iOS
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-iOS

       # Unity 설정 및 빌드
      - name: Setup and Build Unity
        uses: game-ci/unity-builder@v4
        with:
          version: 2023.2.20f1
          targetPlatform: iOS
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Zip the build folder
        run: zip -r ${{ secrets.APP_NAME }}.zip build/iOS

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ secrets.APP_NAME }}-build
          path: build/${{ secrets.APP_NAME }}.zip
